package Adventure.Type;

public enum CommandType {
    END, INVENTORY, HELP, NORD, SOUTH, EAST, WEST, CRAWL, OPEN, CLOSE, DROP, PUT, PUSH, 
    ATTACK, EQUIP, UNEQUIP, PICK_UP, TALK_TO, GIVE, INSERT_PASS_STRONGBOX, 
    INSERT_PASS_ARCHIVE, INSERT_HEX, USE, LOOK, EXAMINE, SAVE, LOAD
}